
name: Go

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - goos: windows
            os: windows-latest
            output-server: lbserver.exe
            output-client: lbclient.exe
            ldflags: "-s -w"
          - goos: darwin
            os: macos-latest
            output-server: lbserver-darwin
            output-client: lbclient-darwin
            ldflags: "-s -w -linkmode external"
          - goos: linux
            os: ubuntu-latest
            output-server: lbserver-linux
            output-client: lbclient-linux
            ldflags: "-s -w -linkmode external"
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        cd server 
        go mod download
        cd ../client 
        go mod download
        cd ..

    - name: Test
      run: |
        cd server
        go test -v ./...
        cd ../client 
        go test -v ./...
        cd ..

    - name: Build Server & Client
      env:
        CGO_ENABLED: 1
        GOOS: ${{ matrix.goos }}
        GOARCH: amd64
      run: |
        cd server
        mkdir -p ${GITHUB_WORKSPACE}/bin/
        go build -ldflags="${{ matrix.ldflags }}" -o ${GITHUB_WORKSPACE}/bin/${{ matrix.output-server }}
        cd ../client 
        go build -ldflags="${{ matrix.ldflags }}" -o ${GITHUB_WORKSPACE}/bin/${{ matrix.output-client }}
        cd ..

 
